-- Enable the moddatetime extension
create extension if not exists moddatetime schema extensions;

create table "public"."Agents" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "role" character varying not null,
    "goal" text not null,
    "backstory" text,
    "memory_enabled" boolean default true,
    "verbose" boolean default false,
    "allow_delegation" boolean default false,
    "max_iterations" smallint default '1'::smallint,
    "max_rpm" smallint,
    "llm_config" jsonb,
    "tools" jsonb,
    "user" uuid
);

comment on table "public"."Agents" is 'Agents table to store AI agents with specific roles';

alter table "public"."Agents" enable row level security;

create table "public"."Tasks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "description" text not null,
    "expected_output" text not null,
    "agent" bigint not null,
    "tools" jsonb,
    "async_execution" boolean default false,
    "config" jsonb,
    "output_json" json,
    "user" uuid,
    "context" bigint[]
);

comment on table "public"."Tasks" is 'Tasks table to store specific assignments';

alter table "public"."Tasks" enable row level security;

CREATE UNIQUE INDEX "Agents_pkey" ON public."Agents" USING btree (id);

CREATE UNIQUE INDEX "Tasks_pkey" ON public."Tasks" USING btree (id);

alter table "public"."Agents" add constraint "Agents_pkey" PRIMARY KEY using index "Agents_pkey";

alter table "public"."Tasks" add constraint "Tasks_pkey" PRIMARY KEY using index "Tasks_pkey";

alter table "public"."Agents" add constraint "Agents_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Agents" validate constraint "Agents_user_fkey";

alter table "public"."Tasks" add constraint "Tasks_agent_fkey" FOREIGN KEY (agent) REFERENCES "Agents"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Tasks" validate constraint "Tasks_agent_fkey";

alter table "public"."Tasks" add constraint "Tasks_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Tasks" validate constraint "Tasks_user_fkey";

grant delete on table "public"."Agents" to "anon";

grant insert on table "public"."Agents" to "anon";

grant references on table "public"."Agents" to "anon";

grant select on table "public"."Agents" to "anon";

grant trigger on table "public"."Agents" to "anon";

grant truncate on table "public"."Agents" to "anon";

grant update on table "public"."Agents" to "anon";

grant delete on table "public"."Agents" to "authenticated";

grant insert on table "public"."Agents" to "authenticated";

grant references on table "public"."Agents" to "authenticated";

grant select on table "public"."Agents" to "authenticated";

grant trigger on table "public"."Agents" to "authenticated";

grant truncate on table "public"."Agents" to "authenticated";

grant update on table "public"."Agents" to "authenticated";

grant delete on table "public"."Agents" to "service_role";

grant insert on table "public"."Agents" to "service_role";

grant references on table "public"."Agents" to "service_role";

grant select on table "public"."Agents" to "service_role";

grant trigger on table "public"."Agents" to "service_role";

grant truncate on table "public"."Agents" to "service_role";

grant update on table "public"."Agents" to "service_role";

grant delete on table "public"."Tasks" to "anon";

grant insert on table "public"."Tasks" to "anon";

grant references on table "public"."Tasks" to "anon";

grant select on table "public"."Tasks" to "anon";

grant trigger on table "public"."Tasks" to "anon";

grant truncate on table "public"."Tasks" to "anon";

grant update on table "public"."Tasks" to "anon";

grant delete on table "public"."Tasks" to "authenticated";

grant insert on table "public"."Tasks" to "authenticated";

grant references on table "public"."Tasks" to "authenticated";

grant select on table "public"."Tasks" to "authenticated";

grant trigger on table "public"."Tasks" to "authenticated";

grant truncate on table "public"."Tasks" to "authenticated";

grant update on table "public"."Tasks" to "authenticated";

grant delete on table "public"."Tasks" to "service_role";

grant insert on table "public"."Tasks" to "service_role";

grant references on table "public"."Tasks" to "service_role";

grant select on table "public"."Tasks" to "service_role";

grant trigger on table "public"."Tasks" to "service_role";

grant truncate on table "public"."Tasks" to "service_role";

grant update on table "public"."Tasks" to "service_role";

-- Add triggers for updated_at timestamps
create trigger handle_agents_updated_at
    before update on public."Agents"
    for each row
    execute function extensions.moddatetime();

create trigger handle_tasks_updated_at
    before update on public."Tasks"
    for each row
    execute function extensions.moddatetime();
