-- Create LLMs table
create table "public"."LLMs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "provider" character varying not null,
    "api_key" character varying,
    "models" character varying[],
    "config" json,
    "user_id" uuid default auth.uid() references auth.users(id) on update cascade on delete set null,
    constraint "LLMs_pkey" primary key ("id")
);

comment on table "public"."LLMs" is 'LLMs table to store language model configurations';

-- Enable RLS
alter table "public"."LLMs" enable row level security;

-- RLS Policies for LLMs
create policy "Users can access their own LLMs"
on "public"."LLMs"
as permissive
for all
to authenticated
using (
    auth.uid() = user_id  -- User's own LLMs
)
with check (
    auth.uid() = user_id  -- Can only create/update their own LLMs
);

-- Grant permissions
grant select, insert, update, delete on table "public"."LLMs" to authenticated;

-- Add trigger for updated_at timestamp
create trigger handle_llms_updated_at
    before update on public."LLMs"
    for each row
    execute function extensions.moddatetime(updated_at);
