-- Create Crews table
create table "public"."Crews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "description" text not null,
    "process" text,
    "verbose" boolean default true,
    "manager_llm" character varying,
    "function_calling_llm" character varying,
    "config" jsonb,
    "max_rpm" integer,
    "language" character varying,
    "memory" boolean default false,
    "memory_config" jsonb,
    "embedder" jsonb,
    "full_output" boolean default false,
    "manager_agent" bigint references "public"."Agents"(id) on update cascade on delete set null,
    "planning" boolean default false,
    "planning_llm" character varying,
    "user_id" uuid default auth.uid() references auth.users(id) on update cascade on delete set null,
    "is_template" boolean default false,
    "is_builtin" boolean default false,
    "template_id" bigint references "public"."Crews"(id),
    "template_version" integer default 1,
    constraint "Crews_pkey" primary key ("id")
);

comment on table "public"."Crews" is 'Crews table to store AI crews with their configurations';
comment on column "public"."Crews"."is_template" is 'Indicates if this record is a template';
comment on column "public"."Crews"."is_builtin" is 'Indicates if this is a built-in template that should not be modified';
comment on column "public"."Crews"."template_id" is 'Reference to the template this instance was created from';
comment on column "public"."Crews"."template_version" is 'Version number of the template';

-- Create junction table for crew agents with ordering
create table "public"."crew_agents" (
    "id" uuid default gen_random_uuid() primary key,
    "crew_id" bigint references "public"."Crews"(id) on delete cascade not null,
    "agent_id" bigint references "public"."Agents"(id) on delete cascade not null,
    "agent_order" integer not null, -- Maintains the order of agents in the crew
    "role" text check (role in ('manager', 'worker')) default 'worker',
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    -- Ensure unique ordering within each crew
    unique(crew_id, agent_order),
    -- Ensure each agent appears only once in a crew
    unique(crew_id, agent_id)
);

-- Create junction table for crew tasks with ordering
create table "public"."crew_tasks" (
    "id" uuid default gen_random_uuid() primary key,
    "crew_id" bigint references "public"."Crews"(id) on delete cascade not null,
    "task_id" bigint references "public"."Tasks"(id) on delete cascade not null,
    "task_order" integer not null, -- Maintains the order of tasks in the crew
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    -- Ensure unique ordering within each crew
    unique(crew_id, task_order),
    -- Ensure each task appears only once in a crew
    unique(crew_id, task_id)
);

-- Create indexes for better query performance
create index idx_crews_is_template on "public"."Crews" (is_template);
create index crew_agents_order_idx on public.crew_agents(crew_id, agent_order);
create index crew_agents_role_idx on public.crew_agents(crew_id, role);
create index crew_tasks_order_idx on public.crew_tasks(crew_id, task_order);

-- Enable RLS
alter table "public"."Crews" enable row level security;
alter table "public"."crew_agents" enable row level security;
alter table "public"."crew_tasks" enable row level security;

-- RLS Policies for Crews
create policy "Users can access their own crews and public crews"
on "public"."Crews"
as permissive
for all
to authenticated
using (
    auth.uid() = user_id  -- User's own crews
    or 
    user_id is null       -- Public crews
)
with check (
    auth.uid() = user_id  -- Can only create/update their own crews
    or 
    user_id is null       -- Or create/update public crews
);

-- RLS Policies for junction tables
create policy "Crew agents are viewable by everyone"
on public.crew_agents
for select
using (true);

create policy "Crew tasks are viewable by everyone"
on public.crew_tasks
for select
using (true);

-- Grant permissions
grant select, insert, update, delete on table "public"."Crews" to authenticated;
grant select, insert, update, delete on table "public"."crew_agents" to authenticated;
grant select, insert, update, delete on table "public"."crew_tasks" to authenticated;

-- Add triggers for updated_at timestamps
create trigger handle_crews_updated_at
    before update on public."Crews"
    for each row
    execute function extensions.moddatetime(updated_at);

create trigger handle_crew_agents_updated_at
    before update on public.crew_agents
    for each row
    execute function extensions.moddatetime(updated_at);

create trigger handle_crew_tasks_updated_at
    before update on public.crew_tasks
    for each row
    execute function extensions.moddatetime(updated_at);

-- Function to reorder agents when one is removed
create or replace function public.reorder_crew_agents()
returns trigger as $$
begin
    -- Reorder remaining agents to close any gaps
    update public.crew_agents
    set agent_order = subquery.new_order
    from (
        select id, row_number() over (partition by crew_id order by agent_order) as new_order
        from public.crew_agents
        where crew_id = old.crew_id
    ) as subquery
    where crew_agents.id = subquery.id;
    return old;
end;
$$ language plpgsql;

-- Function to reorder tasks when one is removed
create or replace function public.reorder_crew_tasks()
returns trigger as $$
begin
    -- Reorder remaining tasks to close any gaps
    update public.crew_tasks
    set task_order = subquery.new_order
    from (
        select id, row_number() over (partition by crew_id order by task_order) as new_order
        from public.crew_tasks
        where crew_id = old.crew_id
    ) as subquery
    where crew_tasks.id = subquery.id;
    return old;
end;
$$ language plpgsql;

-- Add triggers for reordering after deletions
create trigger reorder_agents_after_delete
    after delete on public.crew_agents
    for each row execute function public.reorder_crew_agents();

create trigger reorder_tasks_after_delete
    after delete on public.crew_tasks
    for each row execute function public.reorder_crew_tasks();
