-- Enable the moddatetime extension
create extension if not exists moddatetime schema extensions;

-- Create Agents table
create table "public"."Agents" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "role" character varying not null,
    "goal" text not null,
    "backstory" text,
    "memory_enabled" boolean default true,
    "verbose" boolean default false,
    "allow_delegation" boolean default false,
    "max_iterations" smallint default '1'::smallint,
    "max_rpm" smallint,
    "llm_config" jsonb,
    "tools" jsonb,
    "user_id" uuid default auth.uid() references auth.users(id) on update cascade on delete set null,
    "is_template" boolean default false,
    "is_builtin" boolean default false,
    "template_id" bigint references "public"."Agents"(id),
    "template_version" integer default 1,
    constraint "Agents_pkey" primary key ("id")
);

comment on table "public"."Agents" is 'Agents table to store AI agents with specific roles';
comment on column "public"."Agents"."is_template" is 'Indicates if this record is a template';
comment on column "public"."Agents"."is_builtin" is 'Indicates if this is a built-in template that should not be modified';
comment on column "public"."Agents"."template_id" is 'Reference to the template this instance was created from';
comment on column "public"."Agents"."template_version" is 'Version number of the template';

-- Create Tasks table
create table "public"."Tasks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "description" text not null,
    "expected_output" text not null,
    "agent" bigint references "public"."Agents"(id) on update cascade on delete set null,
    "tools" jsonb,
    "async_execution" boolean default false,
    "config" jsonb,
    "output_json" json,
    "user_id" uuid default auth.uid() references auth.users(id) on update cascade on delete set null,
    "context" bigint[],
    "is_template" boolean default false,
    "is_builtin" boolean default false,
    "template_id" bigint references "public"."Tasks"(id),
    "template_version" integer default 1,
    constraint "Tasks_pkey" primary key ("id")
);

comment on table "public"."Tasks" is 'Tasks table to store specific assignments';
comment on column "public"."Tasks"."is_template" is 'Indicates if this record is a template';
comment on column "public"."Tasks"."is_builtin" is 'Indicates if this is a built-in template that should not be modified';
comment on column "public"."Tasks"."template_id" is 'Reference to the template this instance was created from';
comment on column "public"."Tasks"."template_version" is 'Version number of the template';

-- Create indexes
create index idx_agents_is_template on "public"."Agents" (is_template);
create index idx_tasks_is_template on "public"."Tasks" (is_template);

-- Enable RLS
alter table "public"."Agents" enable row level security;
alter table "public"."Tasks" enable row level security;

-- RLS Policies for Agents
create policy "Users can access their own agents and public agents"
on "public"."Agents"
as permissive
for all
to authenticated
using (
    auth.uid() = user_id  -- User's own agents
    or 
    user_id is null       -- Public agents
)
with check (
    auth.uid() = user_id  -- Can only create/update their own agents
    or 
    user_id is null       -- Or create/update public agents
);

-- RLS Policies for Tasks
create policy "Users can access their own tasks and public tasks"
on "public"."Tasks"
as permissive
for all
to authenticated
using (
    auth.uid() = user_id  -- User's own tasks
    or 
    user_id is null       -- Public tasks
)
with check (
    auth.uid() = user_id  -- Can only create/update their own tasks
    or 
    user_id is null       -- Or create/update public tasks
);

-- Grant permissions
grant select, insert, update, delete on table "public"."Agents" to authenticated;
grant select, insert, update, delete on table "public"."Tasks" to authenticated;

-- Add triggers for updated_at timestamps
create trigger handle_agents_updated_at
    before update on public."Agents"
    for each row
    execute function extensions.moddatetime(updated_at);

create trigger handle_tasks_updated_at
    before update on public."Tasks"
    for each row
    execute function extensions.moddatetime(updated_at);
