create table "public"."Crews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "process" character varying default 'sequential'::character varying,
    "verbose" boolean default false,
    "manager_llm" character varying,
    "function_calling_llm" character varying,
    "config" json,
    "max_rpm" smallint,
    "language" character varying,
    "memory" boolean,
    "memory_config" json,
    "embedder" json,
    "full_output" boolean,
    "manager_agent" bigint,
    "planning" boolean,
    "planning_llm" character varying,
    "user" uuid
);

-- Add trigger for updated_at timestamp
create trigger handle_updated_at before update on "public"."Crews"
    for each row execute procedure moddatetime (updated_at);

alter table "public"."Crews" enable row level security;

CREATE UNIQUE INDEX "Crews_pkey" ON public."Crews" USING btree (id);

alter table "public"."Crews" add constraint "Crews_pkey" PRIMARY KEY using index "Crews_pkey";

alter table "public"."Crews" add constraint "Crews_manager_agent_fkey" FOREIGN KEY (manager_agent) REFERENCES "Agents"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Crews" validate constraint "Crews_manager_agent_fkey";

alter table "public"."Crews" add constraint "Crews_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Crews" validate constraint "Crews_user_fkey";

grant delete on table "public"."Crews" to "anon";

grant insert on table "public"."Crews" to "anon";

grant references on table "public"."Crews" to "anon";

grant select on table "public"."Crews" to "anon";

grant trigger on table "public"."Crews" to "anon";

grant truncate on table "public"."Crews" to "anon";

grant update on table "public"."Crews" to "anon";

grant delete on table "public"."Crews" to "authenticated";

grant insert on table "public"."Crews" to "authenticated";

grant references on table "public"."Crews" to "authenticated";

grant select on table "public"."Crews" to "authenticated";

grant trigger on table "public"."Crews" to "authenticated";

grant truncate on table "public"."Crews" to "authenticated";

grant update on table "public"."Crews" to "authenticated";

grant delete on table "public"."Crews" to "service_role";

grant insert on table "public"."Crews" to "service_role";

grant references on table "public"."Crews" to "service_role";

grant select on table "public"."Crews" to "service_role";

grant trigger on table "public"."Crews" to "service_role";

grant truncate on table "public"."Crews" to "service_role";

grant update on table "public"."Crews" to "service_role";
