create table "public"."LLMs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "provider" character varying not null,
    "api_key" character varying,
    "models" character varying[],
    "config" json
);


alter table "public"."LLMs" enable row level security;

CREATE UNIQUE INDEX "LLMs_pkey" ON public."LLMs" USING btree (id);

alter table "public"."LLMs" add constraint "LLMs_pkey" PRIMARY KEY using index "LLMs_pkey";

grant delete on table "public"."LLMs" to "anon";

grant insert on table "public"."LLMs" to "anon";

grant references on table "public"."LLMs" to "anon";

grant select on table "public"."LLMs" to "anon";

grant trigger on table "public"."LLMs" to "anon";

grant truncate on table "public"."LLMs" to "anon";

grant update on table "public"."LLMs" to "anon";

grant delete on table "public"."LLMs" to "authenticated";

grant insert on table "public"."LLMs" to "authenticated";

grant references on table "public"."LLMs" to "authenticated";

grant select on table "public"."LLMs" to "authenticated";

grant trigger on table "public"."LLMs" to "authenticated";

grant truncate on table "public"."LLMs" to "authenticated";

grant update on table "public"."LLMs" to "authenticated";

grant delete on table "public"."LLMs" to "service_role";

grant insert on table "public"."LLMs" to "service_role";

grant references on table "public"."LLMs" to "service_role";

grant select on table "public"."LLMs" to "service_role";

grant trigger on table "public"."LLMs" to "service_role";

grant truncate on table "public"."LLMs" to "service_role";

grant update on table "public"."LLMs" to "service_role";


